### ISSUE TITLE
Quarkus Tools break the "Members Sort Order" and "Organize Imports"

### ISSUE THREAD

**Issue by leopoldog** [jbosstools/jbosstools-quarkus#188] opened 2022-08-09 15:03 UTC
On Eclipse 2022-06 (4.24.0) build 20220609-1112 (and also the preceding versions), if when installing the JBoss Tools I choose to install the Quarkus Tools the sort operations are broken and always sort in an undefined order.
This problem arise months ago but I can't tell for sure how many month, if I'm not wrong I seen that problem already in January.

The only solution is to uninstall the Quarkus Tools and it's what I've done now (my coworkers have simply switched to IntelliJ and I was ready to do the same if I had failed to find the problem).
Very annoying because he was breaking all the git commit because the reordering of the imports and methods was not correct anymore.

**Comment by jeffmaury** [comment] 2022-08-09 15:06
Duplicate of #179

**Closed by jeffmaury** 2022-08-09 15:06 UTC
